title: Nikhil Paliwal # your name (or website title) here
logo: "/images/nik.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>Computer Vision Engineer<br>
 
  <br>Passionate about research and development of technology related to Computer Vision.<br>
  <a href="https://www.linkedin.com/in/nikhilpaliwal-linkedin">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
image:
  background: "images/port.png"
navbar-img: "images/port.png"
footer-img: "images/port.png"
page-img: "images/port.png"
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
